# Generated by Django 4.0.5 on 2022-06-09 09:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import testing.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('middleName', models.CharField(max_length=30, verbose_name='Отчество')),
                ('rank', models.CharField(choices=[('u', 'Пользователь'), ('j', 'Джуниор'), ('m', 'Мидл'), ('s', 'Сеньор'), ('tl', 'Тимлид')], default='u', max_length=2, verbose_name='Должность')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название проверки')),
                ('score', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], verbose_name='Оценка')),
                ('text', models.CharField(max_length=1500, verbose_name='Основные недостатки')),
                ('elimination_plan', models.FileField(upload_to=testing.models.user_directory_path, verbose_name='План исправления недостатков')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Проверка',
                'verbose_name_plural': 'Проверки',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PunishmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punishment', models.CharField(max_length=300, verbose_name='Наказание')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.profile', verbose_name='Профиль')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.testmodel')),
            ],
            options={
                'verbose_name': 'Наказания',
                'verbose_name_plural': 'Наказания',
            },
        ),
        migrations.CreateModel(
            name='FileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=testing.models.user_directory_path, verbose_name='Файл')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.testmodel')),
            ],
            options={
                'verbose_name': 'Файлы',
                'verbose_name_plural': 'Файлы',
            },
        ),
    ]
