# Generated by Django 4.0.5 on 2022-06-09 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0002_alter_testmodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testing.profile'),
        ),
    ]
